
# Defining Categorical values for each disease

diseasedict = {
    'skin cutaneous melanoma': 0,
    'thyroid carcinoma': 1,
    'sarcoma': 2,
    'prostate adenocarcinoma': 3,
    'pheochromocytoma & paraganglioma': 4,
    'pancreatic adenocarcinoma': 5,
    'head & neck squamous cell carcinoma': 6,
    'esophageal carcinoma': 7,
    'colon adenocarcinoma': 8,
    'cervical & endocervical cancer': 9,
    'breast invasive carcinoma': 10,
    'bladder urothelial carcinoma': 11,
    'testicular germ cell tumor': 12,
    'kidney papillary cell carcinoma': 13,
    'kidney clear cell carcinoma': 14,
    'acute myeloid leukemia': 15,
    'rectum adenocarcinoma': 16,
    'ovarian serous cystadenocarcinoma': 17,
    'lung adenocarcinoma': 18,
    'liver hepatocellular carcinoma': 19,
    'uterine corpus endometrioid carcinoma': 20,
    'glioblastoma multiforme': 21,
    'brain lower grade glioma': 22,
    'uterine carcinosarcoma': 23,
    'thymoma': 24,
    'stomach adenocarcinoma': 25,
    'diffuse large B-cell lymphoma': 26,
    'lung squamous cell carcinoma': 27,
    'mesothelioma': 28,
    'kidney chromophobe': 29,
    'uveal melanoma': 30,
    'cholangiocarcinoma': 31,
    'adrenocortical cancer': 32,
}
